# This compose file will deploy the services, and bootup a postgres server.

#
# SPDX-License-Identifier: Apache-2.0
#

#  cello-dashboard: dashboard service for cello
#  cello-api-engine: api engine service of cello to provide RESTful APIs, listen on 8080
#  cello-postgres: postgres db 

version: '3.2'
services:
  cello-dashboard:
    image: hyperledger/cello-dashboard
    container_name: cello-dashboard
    ports:
      - "${DASHBOARD_SERVICE_PORT}:8081"
    networks:
      - cello-net
    depends_on:
      - cello-api-engine

  # pg database
  cello-postgres:
    image: postgres:11.1
    container_name: cello-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=api_engine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - ${CELLO_STORAGE_PATH:-/opt/cello}/pgdata:/var/lib/postgresql/data
    networks:
      - cello-net

  # api engine service of cello 
  cello-api-engine:
    image: hyperledger/cello-api-engine
    container_name: cello-api-engine
    restart: unless-stopped
    stdin_open: true
    dns_search: .
    environment:
      - GODEBUG=netdns=go
      - DB_NAME=api_engine
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=cello-postgres
      - CELERY_BROKER_URL=redis://redis
      - DB_PORT=5432
      - DEBUG=True
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - API_ENGINE_ADMIN_EMAIL=admin@cello.com
    ports:
      - "8080:8080"
    volumes:
      - ${CELLO_STORAGE_PATH:-/opt/cello}:/opt/cello
    networks:
      - cello-net
    depends_on:
      - cello-postgres

  # cello docker agent may deploy to an individual server. This cofig only serves development purpose.
  cello-docker-agent:
    image: hyperledger/cello-agent-docker
    container_name: cello-docker-agent
    hostname: cello.docker.agent
    restart: always
    ports:
      - "2375:2375"
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_URL=unix://var/run/docker.sock
      - STORAGE_PATH=${CELLO_STORAGE_PATH:-/opt/cello}/hyperledger
    networks:
      cello-net:
        ipv4_address: 172.20.0.10

networks:
  cello-net:
    name: cello-net
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16

volumes:
  cello-api-engine:
  cello-postgres:
  cello-dashboard:
  cello-docker-agent:
