# Generated by Django 5.0 on 2024-01-05 12:02

import Identity.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Identity", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fabricclient",
            name="certificate_related",
        ),
        migrations.RemoveField(
            model_name="fabricclient",
            name="environment",
        ),
        migrations.RemoveField(
            model_name="fabricclient",
            name="network",
        ),
        migrations.RemoveField(
            model_name="fabricclient",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="orderernode",
            name="certificate_related",
        ),
        migrations.RemoveField(
            model_name="orderernode",
            name="environment",
        ),
        migrations.RemoveField(
            model_name="orderernode",
            name="network",
        ),
        migrations.RemoveField(
            model_name="orderernode",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="peernode",
            name="certificate_related",
        ),
        migrations.RemoveField(
            model_name="peernode",
            name="environment",
        ),
        migrations.RemoveField(
            model_name="peernode",
            name="network",
        ),
        migrations.RemoveField(
            model_name="peernode",
            name="organization",
        ),
        migrations.CreateModel(
            name="FabricCA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Identity.environment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            (Identity.models.NodeType["PEER"], "PEER"),
                            (Identity.models.NodeType["ORDERER"], "ORDERER"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Identity.environment",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Identity.network",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Identity.organization",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FabricAdmin",
        ),
        migrations.DeleteModel(
            name="FabricClient",
        ),
        migrations.DeleteModel(
            name="OrdererNode",
        ),
        migrations.DeleteModel(
            name="PeerNode",
        ),
    ]
