version: '3'
services:
  Dev:
    image: postgres:11.1
    container_name: cello-postgres
    restart: always
    environment:
      - POSTGRES_DB=api_engine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
